export const FETCH_ARTICLE_LIST = "FETCH_ARTICLE_LIST"; 
export const FETCH_ARTICLE_LIST_SUCCESS = "FETCH_ARTICLE_LIST_SUCCESS"; 
export const FETCH_ARTICLE_LIST_FAILURE = "FETCH_ARTICLE_LIST_FAILURE"; 

export const FETCH_ARTICLE_DETAIL = "FETCH_ARTICLE_DETAIL"; 
export const FETCH_ARTICLE_DETAIL_SUCCESS = "FETCH_ARTICLE_DETAIL_SUCCESS"; 
export const FETCH_ARTICLE_DETAIL_FAILURE = "FETCH_ARTICLE_DETAIL_FAILURE"; 

export const FETCH_USER_LIST = "FETCH_USER_LIST"; 

export const FETCH_USER_DETAIL = "FETCH_USER_DETAIL"; 
export const FETCH_USER_DETAIL_SUCCESS = "FETCH_USER_DETAIL_SUCCESS"; 
export const FETCH_USER_DETAIL_FAILURE = "FETCH_USER_DETAIL_FAILURE"; 

export const FETCH_MY_DETAIL = "FETCH_MY_DETAIL";

export const UPLOAD_NEW_ARTICLE = "UPLOAD_NEW_ARTICLE";
export const UPLOAD_NEW_ARTICLE_SUCCESS = "UPLOAD_NEW_ARTICLE_SUCCESS";
export const UPLOAD_NEW_ARTICLE_FAILURE = "UPLOAD_NEW_ARTICLE_FAILURE";

export const UPDATE_ARTICLE = "UPDATE_ARTICLE";

export const UPDATE_PROFILE = "UPDATE_PROFILE";

export const DELETE_ARTICLE = "DELETE_ARTICLE"